"""Emit the cohort QC report required by Step 1 §3.2 and §5 exit criteria.

Targets (from spec):
  - ≥400 PD with ≥3 UPDRS3 visits in first 36 months
  - ≥300 PD with baseline UPDRS3 + RNA-seq + ≥1 longitudinal UPDRS3
  - SAA + RNA-seq cohort size
  - DaT-SCAN SBR + RNA-seq cohort size
"""
from __future__ import annotations
from pathlib import Path
import datetime
import pandas as pd

from lib.config import load_config


def main() -> None:
    cfg = load_config()
    df = pd.read_parquet(Path(cfg["results"]["cache_dir"]) / "canonical_clinical.parquet")

    today = datetime.date.today().isoformat()

    # Cohort: visits in first 36 months. Filters out visits with NaN Visit_Months_From_BL
    # (~15%  -  screening or DaT-only visits without UPDRS3/MoCA-stamped INFODT).
    df_36 = df[df["Visit_Months_From_BL"].between(0, 36)]

    # 1. ≥3 UPDRS3 in first 36 months, by cohort
    n_visits = (
        df_36[df_36["UPDRS3_Total"].notna()]
        .groupby(["PATNO", "Cohort_Current"]).size()
        .rename("n_updrs3_visits").reset_index()
    )
    has3 = n_visits[n_visits["n_updrs3_visits"] >= 3]
    counts_has3 = has3["Cohort_Current"].value_counts()

    # 2. PD primary modeling cohort: any RNA-seq sample at EVENT_ID="BL"
    #    + ≥3 UPDRS3 visits in the first 36 months. PPMI's "BL" RNA visit may
    #    not coincide exactly with Visit_Months_From_BL == 0 (which is the
    #    earliest UPDRS3+MoCA-anchored INFODT), so we require RNA at EVENT_ID="BL"
    #    rather than Visit_Months_From_BL == 0 strictly.
    has_baseline_rna = (
        df[(df["EVENT_ID"] == "BL") & df["RNA_HudAlphaID"].notna()]
        ["PATNO"].unique()
    )
    primary_modeling = set(has_baseline_rna) & set(
        has3[has3["Cohort_Current"].isin(["PD", "Prodromal"])]["PATNO"]
    )
    primary_pd = (
        df[(df["PATNO"].isin(primary_modeling)) & (df["Cohort_Current"] == "PD")]
        ["PATNO"].nunique()
    )

    # 3. SAA + RNA-seq
    saa_rna = (
        df[df["SAA_Status"].isin(["Positive", "Negative"]) & df["RNA_HudAlphaID"].notna()]
        ["PATNO"].nunique()
    )

    # 4. DaT-SCAN + RNA-seq
    ds_rna = (
        df[df["DATSCAN_Putamen_Worst"].notna() & df["RNA_HudAlphaID"].notna()]
        ["PATNO"].nunique()
    )

    # Write markdown report
    out_dir = Path(cfg["results"]["qc_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{today}-cohort-qc.md"

    pd_3 = int(counts_has3.get("PD", 0))

    lines = [
        f"# PD-BBB Cohort QC  -  {today}",
        "",
        "## Spec exit criteria",
        "",
        f"- ≥400 PD with ≥3 UPDRS3 visits in first 36 months: **{pd_3}** "
        f"({'PASS' if pd_3 >= 400 else 'BELOW TARGET'})",
        f"- ≥300 PD primary modeling cohort (baseline UPDRS3 + RNA + longitudinal UPDRS3): "
        f"**{primary_pd}** ({'PASS' if primary_pd >= 300 else 'BELOW TARGET'})",
        f"- SAA + RNA-seq overlap: **{saa_rna}** patients",
        f"- DaT-SCAN + RNA-seq overlap: **{ds_rna}** patients",
        "",
        "## Visits-with-≥3-UPDRS3 by cohort",
        "",
        counts_has3.to_markdown(),
        "",
        "## Notes",
        "",
        "- Generated by `code/12_cohort_qc.py` from `canonical_clinical.parquet`.",
        "- 'Visit_Months_From_BL' uses 30.4375 days/month.",
        "- 'Primary modeling cohort' definition matches pre-registration §3.4.",
        "- Visits with NaN Visit_Months_From_BL (screening/DaT-only) are excluded from the 0-36mo window.",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"→ Wrote {out_path}")
    for line in lines[:10]:
        print(line)


if __name__ == "__main__":
    main()
